# Generated by Django 4.2 on 2023-06-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0003_post_is_published_alter_post_image_alter_post_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='Одноразовый код')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Leatherworkers', 'Кожевники'), ('Damage dealers', 'ДД'), ('Heals', 'Хилы'), ('Potion masters', 'Зельевары'), ('Blacksmiths', 'Кузнецы'), ('Guild masters', 'Гилдмастеры'), ('Dealers', 'Торговцы'), ('Spell masters', 'Мастера заклинаний'), ('Quest givers', 'Квестгиверы'), ('Tanks', 'Танки')], max_length=22, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
