# Generated by Django 4.2 on 2023-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Blacksmiths', 'Кузнецы'), ('Potion masters', 'Зельевары'), ('Tanks', 'Танки'), ('Quest givers', 'Квестгиверы'), ('Dealers', 'Торговцы'), ('Damage dealers', 'ДД'), ('Guild masters', 'Гилдмастеры'), ('Leatherworkers', 'Кожевники'), ('Heals', 'Хилы'), ('Spell masters', 'Мастера заклинаний')], max_length=22, verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
