# Generated by Django 4.2 on 2023-07-01 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0006_alter_post_cat_delete_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_com', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Blacksmiths', 'Кузнецы'), ('Potion masters', 'Зельевары'), ('Leatherworkers', 'Кожевники'), ('Quest givers', 'Квестгиверы'), ('Dealers', 'Торговцы'), ('Heals', 'Хилы'), ('Guild masters', 'Гилдмастеры'), ('Damage dealers', 'ДД'), ('Spell masters', 'Мастера заклинаний')], max_length=22, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Картинка поста'),
        ),
    ]
