# Generated by Django 4.2 on 2023-07-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_comment_dislikes_comment_likes_post_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bboard.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Spell masters', 'Мастера заклинаний'), ('Potion masters', 'Зельевары'), ('Blacksmiths', 'Кузнецы'), ('Heals', 'Хилы'), ('Quest givers', 'Квестгиверы'), ('Tanks', 'Танки'), ('Damage dealers', 'ДД'), ('Guild masters', 'Гилдмастеры'), ('Leatherworkers', 'Кожевники'), ('Dealers', 'Торговцы')], max_length=22, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Картинка поста'),
        ),
    ]
