# Generated by Django 4.2 on 2023-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Damage dealers', 'ДД'), ('Spell masters', 'Мастера заклинаний'), ('Guild masters', 'Гилдмастеры'), ('Dealers', 'Торговцы'), ('Heals', 'Хилы'), ('Tanks', 'Танки'), ('Potion masters', 'Зельевары'), ('Quest givers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники')], max_length=22, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/%Y/%m/%d/', verbose_name='Картинка поста'),
        ),
    ]
