# Generated by Django 4.2 on 2023-07-13 10:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_post_cat_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bboard.post', verbose_name='К посту'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Damage dealers', 'ДД'), ('Dealers', 'Торговцы'), ('Quest givers', 'Квестгиверы'), ('Potion masters', 'Зельевары'), ('Guild masters', 'Гилдмастеры'), ('Tanks', 'Танки'), ('Blacksmiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Spell masters', 'Мастера заклинаний'), ('Heals', 'Хилы')], max_length=22, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
