# Generated by Django 4.2 on 2023-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_remove_post_text_post_content_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Одобренные отклики'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Damage dealers', 'ДД'), ('Blacksmiths', 'Кузнецы'), ('Quest givers', 'Квестгиверы'), ('Dealers', 'Торговцы'), ('Potion masters', 'Зельевары'), ('Spell masters', 'Мастера заклинаний'), ('Heals', 'Хилы'), ('Guild masters', 'Гилдмастеры'), ('Leatherworkers', 'Кожевники')], max_length=22, verbose_name='Категория'),
        ),
    ]
