# Generated by Django 4.2 on 2023-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_alter_comment_accepted_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Guild masters', 'Гилдмастеры'), ('Leatherworkers', 'Кожевники'), ('Tanks', 'Танки'), ('Potion masters', 'Зельевары'), ('Quest givers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Heals', 'Хилы'), ('Dealers', 'Торговцы'), ('Damage dealers', 'ДД'), ('Spell masters', 'Мастера заклинаний')], max_length=22, verbose_name='Категория'),
        ),
    ]
