# Generated by Django 4.2 on 2023-07-14 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0014_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Коммент принят'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Heals', 'Хилы'), ('Damage dealers', 'ДД'), ('Leatherworkers', 'Кожевники'), ('Spell masters', 'Мастера заклинаний'), ('Dealers', 'Торговцы'), ('Guild masters', 'Гилдмастеры'), ('Blacksmiths', 'Кузнецы'), ('Potion masters', 'Зельевары'), ('Quest givers', 'Квестгиверы')], max_length=22, verbose_name='Категория'),
        ),
    ]
