# Generated by Django 4.2 on 2023-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0015_alter_comment_accepted_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rejected',
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Damage dealers', 'ДД'), ('Potion masters', 'Зельевары'), ('Tanks', 'Танки'), ('Guild masters', 'Гилдмастеры'), ('Quest givers', 'Квестгиверы'), ('Spell masters', 'Мастера заклинаний'), ('Blacksmiths', 'Кузнецы'), ('Dealers', 'Торговцы'), ('Leatherworkers', 'Кожевники'), ('Heals', 'Хилы')], max_length=22, verbose_name='Категория'),
        ),
    ]
