# Generated by Django 4.2 on 2023-07-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0015_alter_comment_accepted_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="rejected",
        )
    ]
