# Generated by Django 4.2 on 2023-07-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_auto_20230714_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Spell masters', 'Мастера заклинаний'), ('Blacksmiths', 'Кузнецы'), ('Guild masters', 'Гилдмастеры'), ('Leatherworkers', 'Кожевники'), ('Tanks', 'Танки'), ('Dealers', 'Торговцы'), ('Heals', 'Хилы'), ('Damage dealers', 'ДД'), ('Potion masters', 'Зельевары'), ('Quest givers', 'Квестгиверы')], max_length=22, verbose_name='Категория'),
        ),
    ]
