# Generated by Django 4.2 on 2023-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0017_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Spell masters', 'Мастера заклинаний'), ('Heals', 'Хилы'), ('Blacksmiths', 'Кузнецы'), ('Damage dealers', 'ДД'), ('Dealers', 'Торговцы'), ('Guild masters', 'Гилдмастеры'), ('Quest givers', 'Квестгиверы'), ('Potion masters', 'Зельевары'), ('Leatherworkers', 'Кожевники'), ('Tanks', 'Танки')], max_length=22, verbose_name='Категория'),
        ),
    ]
